# Generated by Django 4.2.4 on 2023-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_grade_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='camera_entrance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='camera_exit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
