# Generated by Django 4.2.4 on 2023-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
